import { writeFile } from "fs/promises";
import path from "path";
import url from "url";
import { createClient, Item, ItemUse, Skill, SkillTag } from "data-of-loathing";

const __dirname = url.fileURLToPath(new URL(".", import.meta.url));
const __unsafe_macros_file = path.join(__dirname, "../src/overlappingNames.ts");

function findOverlapping(entries: (Item | Skill)[]): string[] {
  return [
    ...new Set(
      entries
        .filter((entry1) =>
          entries.some(
            (entry2) =>
              entry2 !== entry1 &&
              entry2.name.toLowerCase().includes(entry1.name.toLowerCase()),
          ),
        )
        .map((entry) => entry.name),
    ),
  ];
}

async function main() {
  const client = createClient();
  await client.load();
  const em = client.query;

  const itemQuery = await em.find(Item, {}, { orderBy: { id: "asc" } });
  const skillQuery = await em.find(Skill, {}, { orderBy: { id: "asc" } });

  const overlappingItemNames = findOverlapping(
    itemQuery.filter(
      (item) =>
        item.uses.includes(ItemUse.Combat) ||
        item.uses.includes(ItemUse.CombatReusable),
    ),
  );
  const overlappingSkills = findOverlapping(
    skillQuery.filter((skill) => skill.tags.includes(SkillTag.Combat)),
  );

  let contents = `/** THIS FILE IS AUTOMATICALLY GENERATED. See tools/parseItemSkillNames.ts for more information */\n\n`;

  contents += "export const overlappingItemNames = new Set([\n";
  contents += overlappingItemNames.map((name) => `  "${name}",`).join("\n");
  contents += "\n]);\n\n";

  contents += "export const overlappingSkillNames = new Set([\n";
  contents += overlappingSkills.map((name) => `  "${name}",`).join("\n");
  contents += "\n]);\n";

  await writeFile(__unsafe_macros_file, contents);
}

main();
