/** THIS FILE IS AUTOMATICALLY GENERATED. See tools/parseDefaultProperties.ts for more information */
export type BooleanProperty = ;
export type NumericProperty = ;
export type MonsterProperty = ;
export type LocationProperty = ;
export type StringProperty = ;
export type NumericOrStringProperty = ;
export type FamiliarProperty = ;
export type StatProperty = ;
